//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ESF.R2.Database.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESF_R2Entities : DbContext
    {
        public ESF_R2Entities()
            : base("name=ESF_R2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SourceFile> SourceFiles { get; set; }
        public virtual DbSet<SupplementaryData> SupplementaryDatas { get; set; }
        public virtual DbSet<SupplementaryDataUnitCost> SupplementaryDataUnitCosts { get; set; }
        public virtual DbSet<ValidationError> ValidationErrors { get; set; }
        public virtual DbSet<VersionInfo> VersionInfoes { get; set; }
    
        public virtual int DeleteExistingRecords(Nullable<int> ukprn, string conRefNum)
        {
            var ukprnParameter = ukprn.HasValue ?
                new ObjectParameter("ukprn", ukprn) :
                new ObjectParameter("ukprn", typeof(int));
    
            var conRefNumParameter = conRefNum != null ?
                new ObjectParameter("conRefNum", conRefNum) :
                new ObjectParameter("conRefNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteExistingRecords", ukprnParameter, conRefNumParameter);
        }
    }
}
