//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ESF.R2.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SourceFile()
        {
            this.SupplementaryDatas = new HashSet<SupplementaryData>();
        }
    
        public int SourceFileId { get; set; }
        public string FileName { get; set; }
        public System.DateTime FilePreparationDate { get; set; }
        public string ConRefNumber { get; set; }
        public string UKPRN { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplementaryData> SupplementaryDatas { get; set; }
    }
}
